##################################################################################################
# This is Ingress Controller Configuration for KIBANA
##################################################################################################  

apiVersion: networking.k8s.io/v1beta1

kind: Ingress

metadata:
  name: kibana-routing
  namespace: kube-system
  
  annotations:
     nginx.ingress.kubernetes.io/auth-type: basic
     nginx.ingress.kubernetes.io/auth-secret: yoogeshcredential
     nginx.ingress.kubernetes.io/auth-realm: "***** WARNING:ONLY THE ADMINISTRATOR CAN OPEN THIS WEBSITE *****"

spec:
  rules:
    - host: kibana.fleetman.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana-logging
              servicePort: 5601
              
              
##################################################################################################
# This is Ingress Controller Configuration for SPRINGBOOTSECURITY
##################################################################################################  

apiVersion: networking.k8s.io/v1beta1

kind: Ingress

metadata:
  name: webapp-routing

spec:
  rules:
    - host: fleetman.com
      http:
        paths:
          - path: /
            backend:
              serviceName: twm-webapp
              servicePort: 80
                            