##################################################################################################
# This is Ingress Controller Configuration
# from version 2.24 of k8s [You can check the current version using 'kubectl version']
##################################################################################################  

apiVersion: networking.k8s.io/v1beta1

kind: Ingress

metadata:
  name: kibana-routing
  namespace: kube-system

spec:
  rules:
    - host: fleetman.com
      http:
        paths:
          - path: /kibana
            backend:
              serviceName: kibana-logging
              servicePort: 5601
              
---

##################################################################################################
# This is Ingress Controller Configuration
# from version 2.24 of k8s [You can check the current version using 'kubectl version']
##################################################################################################  

apiVersion: networking.k8s.io/v1beta1

kind: Ingress

metadata:
  name: secure-routing
  annotations:
     nginx.ingress.kubernetes.io/auth-type: basic
     nginx.ingress.kubernetes.io/auth-secret: yoogeshcredential
     nginx.ingress.kubernetes.io/auth-realm: "***** WARNING:ONLY THE ADMINISTRATOR CAN OPEN THIS WEBSITE *****"

spec:
  rules:
    - host: fleetman.com
      http:
        paths:
          - path: /httpd
            backend:
              serviceName: yoogesh-httpd-server
              servicePort: 80
              
---

##################################################################################################
# This is Ingress Controller Configuration
# from version 2.24 of k8s [You can check the current version using 'kubectl version']
##################################################################################################  

apiVersion: networking.k8s.io/v1beta1

kind: Ingress

metadata:
  name: public-routing

spec:
  rules:
    - host: fleetman.com
      http:
        paths:
          - path: /
            backend:
              serviceName: twm-webapp
              servicePort: 80
                            