########################################################################################################
# This is Cluster Based Authentication (CBAC)

# Normally a Role Based Authentication (RBAC) is for only one namespace. so if you want to give an access to the user who can move around the cluster
# and has an access to create and deploy the application to any namespace he wants then go for CBAC.
######################################################################################################## 

apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRole

metadata: 
  name: new-joiner
  
rules:

- apiGroups: ["", "apps", "autoscaling", "extensions"]
  resources: ["*"]                                         # pods, services, deployments...
  verbs: ["get", "list", "watch"]                          # User is get Only a read acess i.e. get call, listout calls and watch for change


---

apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding

metadata:
  name: CLUSTER_ROLE_BINDING_NEW_JOINER

subjects:

- kind: User
  name: ysharma@kksoftware.com
  
- kind: User
  name: sushila@kksoftware.com

roleRef:
  kind: ClusterRole
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
  