########################################################################################################
#Role Based Authentication (RBAC)
######################################################################################################## 

apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata: 
  name: new-joiner
  namespace: playground
  
rules:

- apiGroups: ["", "apps"]
  resources: ["*"] 
  verbs: ["get", "list", "watch"]
  
  
---
apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: ROLE_BINDING_NEW_JOINER
  namespace: playground

subjects:

- kind: User
  name: ysharma@kksoftware.com
  
- kind: User
  name: sushila@kksoftware.com

roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
 