apiVersion: networking.istio.io/v1alpha3

kind: VirtualService

metadata:
  name: istio-ingress-virtual-service-monitor-configuration
  namespace: istio-system
  
spec:
  hosts:
    - monitor.fleetman.com
  gateways:
    - istio-ingress-firewall-yoogesh
    
  http:
  
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: prometheus.istio-system.svc.cluster.local
          port:
            number: 9090
            
#    - match:
#      - uri:
#          prefix: /kiali
#      route:
#      - destination:
#          host: kiali.istio-system.svc.cluster.local
#          port:
#            number: 20001
