apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: python-cronjob

#CronJob specification starts from here
spec:
  #Runs every 5 min
  schedule: "*/1 * * * *"
  jobTemplate: 
  
     #Job specification starts from here
     spec:
       template:
       
          #pod specifiction starts from here  
          spec:
            containers:
            - name: long-job
              image: python:rc-slim
              command: ["python"]
              args: ["-c", "import time; print('Job started.....'); time.sleep(30); print('Job completed.....')"]
            restartPolicy: Never
            
       backoffLimit: 2
  